<?php global $site_url; ?>
<div class="flex items-center justify-center px-4 h-[80vh]">
    <form id="sign-form" method="post" class="sign-form w-[400px] ">
        <div class="input-group mb-4">
            <label for="" class="mb-2 text-[var(--common-color)] transition duration-300  block font-medium">Full Name</label>
            <input required name="name" placeholder="John Doe" type="text"
                class="hover:border-[var(--zon-theme-color)] rounded-2xl text-[var(--common-color)] bg-[var(--sidebar-option-hover-bg-color)] focus:outline-[var(--zon-theme-color)] px-4 w-full py-4  border border-[var(--zon-comment-input-b-color)] " />
        </div>
        <div class="input-group mb-4">
            <label for="" class="mb-2 text-[var(--common-color)] transition duration-300  block font-medium">Email</label>
            <input required name="email" placeholder="example@mvnthemes.com" type="email"
                class="px-4 w-full py-4 rounded-2xl text-[var(--common-color)] bg-[var(--sidebar-option-hover-bg-color)] hover:border-[var(--zon-theme-color)] focus:outline-[var(--zon-theme-color)]   border border-[var(--zon-comment-input-b-color)] " />
        </div>
        <div class="input-group mb-4">
            <label for="" class="mb-2 text-[var(--common-color)] transition duration-300  block font-medium">Username</label>
            <input required name="username" placeholder="johndoe" type="username"
                class="px-4 w-full py-4 rounded-2xl text-[var(--common-color)] bg-[var(--sidebar-option-hover-bg-color)] hover:border-[var(--zon-theme-color)] focus:outline-[var(--zon-theme-color)]   border border-[var(--zon-comment-input-b-color)] " />
        </div>
        <div class="input-group mb-4">
            <label for="" class="mb-2 text-[var(--common-color)] transition duration-300  block font-medium">Password</label>
            <input required name="password" placeholder="#######" type="password"
                class="px-4 w-full py-4 rounded-2xl text-[var(--common-color)] bg-[var(--sidebar-option-hover-bg-color)] hover:border-[var(--zon-theme-color)] focus:outline-[var(--zon-theme-color)]   border border-[var(--zon-comment-input-b-color)] " />
        </div>
        <input type="text" name="signup" hidden />
        <button  type="submit" class="w-full rounded-3xl disabled:opacity-70 mt-3 py-3 text-white bg-[var(--zon-theme-color)] px-4">Login</button>
        <p style="color: var(--zon-muted-color);" class="text-center mt-3 mb-3">You have an acoount? | <a class="hover:text-[var(--zon-theme-color)] hover:underline" data-ajax="true" data-href="/login" href="<?php echo $site_url ?>login">Login</a> </p>
    </form>
</div>