<?php
global $zon;
$page = getPageById($zon['page'][1]);
?>
<div class="zon-container">
    <div class="mt-6">
        <h1 class="text-3xl font-bold  ">
            <?php echo $page['title'] ?>
        </h1>
        <p class="text-sm mt-3">
            <?php echo $page['desc'] ?>
        </p>
        <div class="page-content mt-6">
            <?php echo $page['content'] ?>
        </div>
    </div>
</div>