<div class="zon-container">
    <h1 class="text-3xl capitalize mb-8 mt-3 block capitalize font-bold page-heading" >Newest Games</h1>
    <div id="zon_games" class="game__grid home__game__grid"></div>
    <div id="zon-loader" class="game__grid">
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
        <div class="game" style="background: #fff; border-radius: 20px; box-shadow: 0px 0px 40px 0px #dcdcdc;"></div>
    </div>
</div>