<?php global $site_url; ?>
<div class="flex items-center wow <?php echo $zon['config']['animate_class'] ?> justify-center px-4 h-[80vh]">
    <form id="login-form" method="post" class="login-form w-[400px] ">
        <div class="input-group mb-4">
            <label for="" class="mb-2 transition duration-300 text-[var(--common-color)] block font-medium">Email & Username</label>
            <input required name="usernameEmail" placeholder="zontal@mvnthemes.com" type="text"
                class="hover:border-[var(--zon-theme-color)] focus:outline-[var(--zon-theme-color)] px-4 w-full py-4 rounded-2xl text-[var(--common-color)] bg-[var(--sidebar-option-hover-bg-color)] border border-[var(--zon-comment-input-b-color)] " />
        </div>
        <div class="input-group">
            <label for="" class="mb-2 transition duration-300 text-[var(--common-color)] block font-medium">Password</label>
            <input required name="password" placeholder="#######" type="password"
                class="px-4 w-full py-4 hover:border-[var(--zon-theme-color)] focus:outline-[var(--zon-theme-color)] rounded-2xl text-[var(--common-color)] bg-[var(--sidebar-option-hover-bg-color)] border border-[var(--zon-comment-input-b-color)] " />
        </div>
        <button type="submit" class="w-full disabled:opacity-70 rounded-lg mt-6 py-3 text-white bg-[var(--zon-theme-color)] rounded-3xl px-4">Login</button>
    </form>
</div>