<?php global $zon, $site_url;
$data = [];
if (count(FeaturedGames()) > 0) {
    $data = FeaturedGames()[0];
    $cn = $data['game_category'];
    $c = runner("SELECT * FROM zon_category WHERE name='$cn'")[0];
    $data['slug'] = $c['slug'];
}
?>
<div class="active-game-img">
    <div class="overlay"></div>
    <div style="background-image: url(<?= $data['game_banner_url'] === '' ? $data['game_image_url'] : $data['game_banner_url'] ?>);"
        id="bg-game-img" class="image"></div>
</div>

<?php if (count(FeaturedGames()) > 0) { ?>
    <div id="dynamicContent" class="dynamic-game-content wow <?php echo $zon['config']['animate_class'] ?>">
        <h1 class="content-title"><?= $data['game_name'] ?></h1>
        <div class="flex gap-2 flex-col-1200 items-center">
            <div class="flex items-center gap-4">
                <img src="<?= $data['game_image_url'] ?>" class="content-icon" alt="<?= $zon['config']['site_name'] ?>" />
                <div class="flex flex-col">
                    <h3 class="text-2xl text-[var(--common-color)] content-title-sm"><?= $data['game_name'] ?></h3>
                    <a data-ajax="true" data-href="/<?= $data['slug'] ?>"
                        class="text-[var(--common-color-muted)] text-lg content-category capitalize"
                        href="<?= $site_url ?><?= $data['slug'] ?>"><?= $data['game_category'] ?></a>
                </div>
            </div>
            <a data-ajax="true" data-href="/<?= $data['game_slug'] ?>" href="<?= $site_url ?><?= $data['game_slug'] ?>"
                class="play-button">Play Now</a>
        </div>
    </div>
    <div class="game-slide-outer featured-games relative h-full w-full">
        <div onclick="SlideLeft(460, this)" class="left slide-controller d-none">
            <div class="icon">&LeftArrow;</div>
        </div>
        <div class="game-slider-container scroll-none">
            <div style="width: calc(460px * <?= $zon['config']['section_games_limit'] > count(FeaturedGames()) ? count(FeaturedGames()) : $zon['config']['section_games_limit'] ?>);"
                class="game-slider">
                <?php
                $i = 0;
                foreach (FeaturedGames() as $game) { ?>
                    <div <?php if ($i != 0) { ?> onclick="AutoSlide(470, this)" <?php } ?>
                        data-game-name="<?= $game['game_name'] ?>" data-game-icon="<?= $game['game_image_url'] ?>"
                        data-bg-image="<?= $game['game_banner_url'] === '' ? $game['game_image_url'] : $game['game_banner_url'] ?>"
                        data-game-category="<?= $game['game_category'] ?>"
                        data-game-link="<?= $site_url . makeSlug($game['game_name']) ?>"
                        data-game-category-link="<?= $site_url . makeSlug($game['game_category']) ?>"
                        class="game-card wow <?php echo $zon['config']['animate_class'] ?> slide">
                        <div data-logo-src="<?= $zon['logo'] ?>" class="game-poster cursor-pointer no-spa">
                            <div class="loader">
                                <div class="fadeLogo">
                                    <img src="<?= $zon['logo'] ?>" alt="<?= $zon['config']['site_name'] ?>" />
                                </div>
                            </div>
                            <img src="<?= $game['game_banner_url'] === '' ? $game['game_image_url'] : $game['game_banner_url'] ?>"
                                onerror="this.previousElementSibling.classList.add('active')" loading="lazy"
                                alt="<?= $game['game_name'] ?>" />
                            <?php if ($game['game_played'] >= $zon['config']['popular_views']) { ?>
                                <div class="badge hot">
                                    <svg width="20px" height="20px" viewBox="0 0 24 24" stroke-width="2" fill="none"
                                        xmlns="http://www.w3.org/2000/svg" color="#000000">
                                        <path d="M13 10V3L5 14H11V21L19 10H13Z" stroke="#000000" stroke-width="2"
                                            stroke-linecap="round" stroke-linejoin="round">
                                        </path>
                                    </svg>
                                </div>
                            <?php } ?>

                            <?php if ($game['game_played'] == 0) { ?>
                                <div class="badge new">
                                    <svg width="20px" height="20px" stroke-width="2" viewBox="0 0 24 24" fill="none"
                                        xmlns="http://www.w3.org/2000/svg" color="#000000">
                                        <path
                                            d="M15.8189 13.3287L10.4948 19.3183C9.69924 20.2134 8.30076 20.2134 7.50518 19.3183L2.18109 13.3287C1.50752 12.571 1.50752 11.429 2.18109 10.6713L7.50518 4.68167C8.30076 3.78664 9.69924 3.78664 10.4948 4.68167L15.8189 10.6713C16.4925 11.429 16.4925 12.571 15.8189 13.3287Z"
                                            stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                        </path>
                                        <path
                                            d="M12 6.375L13.5052 4.68167C14.3008 3.78664 15.6992 3.78664 16.4948 4.68167L21.8189 10.6713C22.4925 11.429 22.4925 12.571 21.8189 13.3287L16.4948 19.3183C15.6992 20.2134 14.3008 20.2134 13.5052 19.3183L12 17.625"
                                            stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                        </path>
                                    </svg>
                                </div>
                            <?php } ?>
                            <div class="played-badge">
                                <svg width="20" height="20" viewBox="0 0 48 48" fill="none" xmlns="http://www.w3.org/2000/svg">
                                    <path
                                        d="M32 18H16C9.37258 18 4 23.3726 4 30C4 36.6274 9.37258 42 16 42H32C38.6274 42 44 36.6274 44 30C44 23.3726 38.6274 18 32 18Z"
                                        fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                    <path d="M16 26V34" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path d="M12 30H20" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path d="M24 16V9.71429H32V4" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                        stroke-linejoin="round" />
                                    <path
                                        d="M32 34C34.2091 34 36 32.2091 36 30C36 27.7909 34.2091 26 32 26C29.7909 26 28 27.7909 28 30C28 32.2091 29.7909 34 32 34Z"
                                        fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                </svg>
                                <span><?= $game['game_played'] ?></span>
                            </div>
                        </div>
                        <div class="game-details flex flex-col px-2 mt-2">
                            <h2 class="text-2xl text-[var(--common-color)] game-name" href="#"><?= $game['game_name'] ?></h2>
                            <p class="text-md text-[var(--common-color-muted)] mt-1 capitalize"><?= $game['game_category'] ?>
                            </p>
                        </div>
                    </div>
                    <?php $i++;
                } ?>
            </div>
        </div>
        <div onclick="SlideRight(460, this)" class="right slide-controller">
            <div class="icon">&RightArrow;</div>
        </div>
    </div>

    <?php if (count(getNewGames()) > 0) { ?>
        <section class="new-games dynamic-section wow <?php echo $zon['config']['animate_class'] ?> mt-12">
            <h2 class="section-heading">
                New Release
                <a data-ajax="true" data-href="/new-games" href="<?= $site_url ?>new-games" class="more">&RightArrow;</a>
            </h2>
            <div class="flex gap-10 items-center mt-6">
                <!-- // section badge  -->
                <div class="new-games-badge-bx badge-bx <?= getAdById(6, 'code') ? '' : 'center' ?> ">
                    <?php if (getAdById(6, 'code')) { ?>
                        <?= getAdById(6, 'code') ?>
                    <?php } else { ?>
                        <div class="icon">
                            <svg width="20px" height="20px" stroke-width="2" viewBox="0 0 24 24" fill="none"
                                xmlns="http://www.w3.org/2000/svg" color="#000000">
                                <path
                                    d="M15.8189 13.3287L10.4948 19.3183C9.69924 20.2134 8.30076 20.2134 7.50518 19.3183L2.18109 13.3287C1.50752 12.571 1.50752 11.429 2.18109 10.6713L7.50518 4.68167C8.30076 3.78664 9.69924 3.78664 10.4948 4.68167L15.8189 10.6713C16.4925 11.429 16.4925 12.571 15.8189 13.3287Z"
                                    stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                </path>
                                <path
                                    d="M12 6.375L13.5052 4.68167C14.3008 3.78664 15.6992 3.78664 16.4948 4.68167L21.8189 10.6713C22.4925 11.429 22.4925 12.571 21.8189 13.3287L16.4948 19.3183C15.6992 20.2134 14.3008 20.2134 13.5052 19.3183L12 17.625"
                                    stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                </path>
                            </svg>
                        </div>
                    <?php } ?>
                </div>
                <!-- // game slider  -->
                <div class="game-slide-outer extra-space cards-sm relative h-full w-full">
                    <div onclick="SlideLeft(370, this)" class="left slide-controller d-none">
                        <div class="icon">&LeftArrow;</div>
                    </div>
                    <div class="game-slider-container scroll-none">
                        <div style="width: calc(350px * <?= $zon['config']['section_games_limit'] > count(getNewGames()) ? count(getNewGames()) : $zon['config']['section_games_limit'] ?>);"
                            class="game-slider">
                            <?php ?>
                            <?php foreach (getNewGames() as $game) {
                                $cn = $game['game_category'];
                                $c = runner("SELECT * FROM zon_category WHERE name='$cn'")[0];
                                $game['slug'] = $c['slug'];
                                ?>
                                <div class="game-card slide">
                                    <a data-ajax="true" data-href="/<?= $game['game_slug'] ?>"
                                        href="<?= $site_url . $game['game_slug'] ?>" data-logo-src="<?= $zon['logo'] ?>"
                                        class=" game-poster">
                                        <div class="loader">
                                            <div class="fadeLogo">
                                                <img src="<?= $zon['logo'] ?>" alt="<?= $zon['config']['site_name'] ?>" />
                                            </div>
                                        </div>
                                        <img src="<?= $game['game_banner_url'] === '' ? $game['game_image_url'] : $game['game_banner_url'] ?>"
                                            onerror="this.previousElementSibling.classList.add('active')" loading="lazy"
                                            alt="<?= $game['game_name'] ?>" />

                                        <?php if ($game['game_played'] == 0) { ?>
                                            <div class="badge new">
                                                <svg width="20px" height="20px" stroke-width="2" viewBox="0 0 24 24" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg" color="#000000">
                                                    <path
                                                        d="M15.8189 13.3287L10.4948 19.3183C9.69924 20.2134 8.30076 20.2134 7.50518 19.3183L2.18109 13.3287C1.50752 12.571 1.50752 11.429 2.18109 10.6713L7.50518 4.68167C8.30076 3.78664 9.69924 3.78664 10.4948 4.68167L15.8189 10.6713C16.4925 11.429 16.4925 12.571 15.8189 13.3287Z"
                                                        stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                        stroke-linejoin="round">
                                                    </path>
                                                    <path
                                                        d="M12 6.375L13.5052 4.68167C14.3008 3.78664 15.6992 3.78664 16.4948 4.68167L21.8189 10.6713C22.4925 11.429 22.4925 12.571 21.8189 13.3287L16.4948 19.3183C15.6992 20.2134 14.3008 20.2134 13.5052 19.3183L12 17.625"
                                                        stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                        stroke-linejoin="round">
                                                    </path>
                                                </svg>
                                            </div>
                                        <?php } ?>
                                        <div class="played-badge">
                                            <svg width="20" height="20" viewBox="0 0 48 48" fill="none"
                                                xmlns="http://www.w3.org/2000/svg">
                                                <path
                                                    d="M32 18H16C9.37258 18 4 23.3726 4 30C4 36.6274 9.37258 42 16 42H32C38.6274 42 44 36.6274 44 30C44 23.3726 38.6274 18 32 18Z"
                                                    fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                                <path d="M16 26V34" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                    stroke-linejoin="round" />
                                                <path d="M12 30H20" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                    stroke-linejoin="round" />
                                                <path d="M24 16V9.71429H32V4" stroke="#000000" stroke-width="2"
                                                    stroke-linecap="round" stroke-linejoin="round" />
                                                <path
                                                    d="M32 34C34.2091 34 36 32.2091 36 30C36 27.7909 34.2091 26 32 26C29.7909 26 28 27.7909 28 30C28 32.2091 29.7909 34 32 34Z"
                                                    fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                            </svg>
                                            <span><?= $game['game_played'] ?></span>
                                        </div>
                                    </a>
                                    <div class="game-details flex flex-col px-2 mt-2">
                                        <a data-ajax="true" data-href="/<?= $game['game_slug'] ?>"
                                            class="text-2xl text-[var(--common-color)] game-name"
                                            href="<?= $site_url . $game['game_slug'] ?>"><?= $game['game_name'] ?></a>
                                        <a data-ajax="true" data-href="/<?= $game['slug'] ?>"
                                            class="text-md text-[var(--common-color-muted)] mt-1 capitalize"
                                            href="<?= $site_url . $game['slug'] ?>"><?= $game['game_category'] ?></a>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div onclick="SlideRight(350, this)" class="right slide-controller">
                        <div class="icon">&RightArrow;</div>
                    </div>
                </div>
            </div>
        </section>
    <?php } ?>

    <?php if (count(getPopularGames()) > 0) { ?>
        <!-- // popular games section -->
        <section class="new-games dynamic-section wow <?php echo $zon['config']['animate_class'] ?> mt-12">
            <h2 class="section-heading">
                Popular Games
                <a data-ajax="true" data-href="/popular-games" href="<?= $site_url ?>popular-games"
                    class="more">&RightArrow;</a>
            </h2>
            <div class="flex gap-10 items-center mt-6">
                <div class="popular-games-badge-bx badge-bx <?= getAdById(6, 'code') ? '' : 'center' ?>">
                    <!-- // section badge  -->
                    <?php if (getAdById(6, 'code')) { ?>
                        <?= getAdById(6, 'code') ?>
                    <?php } else { ?>
                        <div class="icon">
                            <svg width="20px" height="20px" viewBox="0 0 24 24" stroke-width="2" fill="none"
                                xmlns="http://www.w3.org/2000/svg" color="#000000">
                                <path d="M13 10V3L5 14H11V21L19 10H13Z" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                    stroke-linejoin="round">
                                </path>
                            </svg>
                        </div>
                        <!-- <span>Popular Games</span> -->
                    <?php } ?>
                </div>
                <!-- // game slider  -->
                <div class="game-slide-outer extra-space cards-sm relative h-full w-full">
                    <div onclick="SlideLeft(350, this)" class="left slide-controller d-none">
                        <div class="icon">&LeftArrow;</div>
                    </div>
                    <div class="game-slider-container scroll-none">
                        <div style="width: calc(350px * <?= $zon['config']['section_games_limit'] > count(getPopularGames()) ? count(getPopularGames()) : $zon['config']['section_games_limit'] ?>);"
                            class="game-slider">
                            <?php ?>
                            <?php foreach (getPopularGames() as $game) {
                                $cn = $game['game_category'];
                                $c = runner("SELECT * FROM zon_category WHERE name='$cn'")[0];
                                $game['slug'] = $c['slug'];
                                ?>
                                <div class="game-card slide">
                                    <a data-ajax="true" data-href="/<?= $game['game_slug'] ?>"
                                        href="<?= $site_url . $game['game_slug'] ?>" data-logo-src="<?= $zon['logo'] ?>"
                                        class=" game-poster">
                                        <div class="loader">
                                            <div class="fadeLogo">
                                                <img src="<?= $zon['logo'] ?>" alt="<?= $zon['config']['site_name'] ?>" />
                                            </div>
                                        </div>
                                        <img src="<?= $game['game_banner_url'] === '' ? $game['game_image_url'] : $game['game_banner_url'] ?>"
                                            onerror="this.previousElementSibling.classList.add('active')" loading="lazy"
                                            alt="<?= $game['game_name'] ?>" />
                                        <?php if ($game['game_played'] >= $zon['config']['popular_views']) { ?>
                                            <div class="badge hot">
                                                <svg width="20px" height="20px" viewBox="0 0 24 24" stroke-width="2" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg" color="#000000">
                                                    <path d="M13 10V3L5 14H11V21L19 10H13Z" stroke="#000000" stroke-width="2"
                                                        stroke-linecap="round" stroke-linejoin="round">
                                                    </path>
                                                </svg>
                                            </div>
                                        <?php } ?>

                                        <?php if ($game['game_played'] == 0) { ?>
                                            <div class="badge new">
                                                <svg width="20px" height="20px" stroke-width="2" viewBox="0 0 24 24" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg" color="#000000">
                                                    <path
                                                        d="M15.8189 13.3287L10.4948 19.3183C9.69924 20.2134 8.30076 20.2134 7.50518 19.3183L2.18109 13.3287C1.50752 12.571 1.50752 11.429 2.18109 10.6713L7.50518 4.68167C8.30076 3.78664 9.69924 3.78664 10.4948 4.68167L15.8189 10.6713C16.4925 11.429 16.4925 12.571 15.8189 13.3287Z"
                                                        stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                        stroke-linejoin="round">
                                                    </path>
                                                    <path
                                                        d="M12 6.375L13.5052 4.68167C14.3008 3.78664 15.6992 3.78664 16.4948 4.68167L21.8189 10.6713C22.4925 11.429 22.4925 12.571 21.8189 13.3287L16.4948 19.3183C15.6992 20.2134 14.3008 20.2134 13.5052 19.3183L12 17.625"
                                                        stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                        stroke-linejoin="round">
                                                    </path>
                                                </svg>
                                            </div>
                                        <?php } ?>
                                        <div class="played-badge">
                                            <svg width="20" height="20" viewBox="0 0 48 48" fill="none"
                                                xmlns="http://www.w3.org/2000/svg">
                                                <path
                                                    d="M32 18H16C9.37258 18 4 23.3726 4 30C4 36.6274 9.37258 42 16 42H32C38.6274 42 44 36.6274 44 30C44 23.3726 38.6274 18 32 18Z"
                                                    fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                                <path d="M16 26V34" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                    stroke-linejoin="round" />
                                                <path d="M12 30H20" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                    stroke-linejoin="round" />
                                                <path d="M24 16V9.71429H32V4" stroke="#000000" stroke-width="2"
                                                    stroke-linecap="round" stroke-linejoin="round" />
                                                <path
                                                    d="M32 34C34.2091 34 36 32.2091 36 30C36 27.7909 34.2091 26 32 26C29.7909 26 28 27.7909 28 30C28 32.2091 29.7909 34 32 34Z"
                                                    fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                            </svg>
                                            <span><?= $game['game_played'] ?></span>
                                        </div>
                                    </a>
                                    <div class="game-details flex flex-col px-2 mt-2">
                                        <a data-ajax="true" data-href="/<?= $game['game_slug'] ?>"
                                            class="text-2xl text-[var(--common-color)] game-name"
                                            href="<?= $site_url . makeSlug($game['game_name']) ?>"><?= $game['game_name'] ?></a>
                                        <a data-ajax="true" data-href="/<?= $game['slug'] ?>"
                                            class="text-md text-[var(--common-color-muted)] mt-1 capitalize"
                                            href="<?= $site_url . $game['slug'] ?>"><?= $game['game_category'] ?></a>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div onclick="SlideRight(350, this)" class="right slide-controller">
                        <div class="icon">&RightArrow;</div>
                    </div>
                </div>
            </div>
        </section>
    <?php } ?>


    <?php foreach (DynamicSection() as $section) { ?>
        <?php if (count(GameByCategoryName($section['section_category'], $zon['config']['section_games_limit'])) > 0) { ?>
            <section class="new-games wow <?php echo $zon['config']['animate_class'] ?> dynamic-section mt-12">
                <h2 class="section-heading">
                    <?= $section['section_name'] ?>
                    <a data-ajax="true"
                        data-href="/<?php echo urlencode(makeSlug(getCategoryNameById($section['section_category']))) ?>"
                        href="<?php echo $site_url ?><?php echo urlencode(makeSlug(getCategoryNameById($section['section_category']))) ?>"
                        class="more">&RightArrow;</a>
                </h2>
                <!-- // game slider  -->
                <div class="game-slide-outer cards-sm relative h-full w-full">
                    <div onclick="SlideLeft(370, this)" class="left slide-controller d-none">
                        <div class="icon">&LeftArrow;</div>
                    </div>
                    <div class="game-slider-container scroll-none">
                        <div style="width: calc(350px * <?= $zon['config']['section_games_limit'] > count(GameByCategoryName($section['section_category'], $zon['config']['section_games_limit'])) ? count(GameByCategoryName($section['section_category'], $zon['config']['section_games_limit'])) : $zon['config']['section_games_limit'] ?>);"
                            class="game-slider">
                            <?php ?>
                            <?php foreach (GameByCategoryName($section['section_category'], $zon['config']['section_games_limit']) as $game) {
                                $cn = $game['game_category'];
                                $c = runner("SELECT * FROM zon_category WHERE name='$cn'")[0];
                                $game['slug'] = $c['slug'];
                                ?>
                                <div class="game-card slide">
                                    <a data-ajax="true" data-href="/<?= $game['game_slug'] ?>"
                                        href="<?= $site_url . $game['game_slug'] ?>" data-logo-src="<?= $zon['logo'] ?>"
                                        class=" game-poster">
                                        <div class="loader">
                                            <div class="fadeLogo">
                                                <img src="<?= $zon['logo'] ?>" alt="<?= $zon['config']['site_name'] ?>" />
                                            </div>
                                        </div>
                                        <img src="<?= $game['game_banner_url'] === '' ? $game['game_image_url'] : $game['game_banner_url'] ?>"
                                            onerror="this.previousElementSibling.classList.add('active')" loading="lazy"
                                            alt="<?= $game['game_name'] ?>" />
                                        <?php if ($game['game_played'] >= $zon['config']['popular_views']) { ?>
                                            <div class="badge hot">
                                                <svg width="20px" height="20px" viewBox="0 0 24 24" stroke-width="2" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg" color="#000000">
                                                    <path d="M13 10V3L5 14H11V21L19 10H13Z" stroke="#000000" stroke-width="2"
                                                        stroke-linecap="round" stroke-linejoin="round">
                                                    </path>
                                                </svg>
                                            </div>
                                        <?php } ?>

                                        <?php if ($game['game_played'] == 0) { ?>
                                            <div class="badge new">
                                                <svg width="20px" height="20px" stroke-width="2" viewBox="0 0 24 24" fill="none"
                                                    xmlns="http://www.w3.org/2000/svg" color="#000000">
                                                    <path
                                                        d="M15.8189 13.3287L10.4948 19.3183C9.69924 20.2134 8.30076 20.2134 7.50518 19.3183L2.18109 13.3287C1.50752 12.571 1.50752 11.429 2.18109 10.6713L7.50518 4.68167C8.30076 3.78664 9.69924 3.78664 10.4948 4.68167L15.8189 10.6713C16.4925 11.429 16.4925 12.571 15.8189 13.3287Z"
                                                        stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                    </path>
                                                    <path
                                                        d="M12 6.375L13.5052 4.68167C14.3008 3.78664 15.6992 3.78664 16.4948 4.68167L21.8189 10.6713C22.4925 11.429 22.4925 12.571 21.8189 13.3287L16.4948 19.3183C15.6992 20.2134 14.3008 20.2134 13.5052 19.3183L12 17.625"
                                                        stroke="#000000" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">
                                                    </path>
                                                </svg>
                                            </div>
                                        <?php } ?>
                                        <div class="played-badge">
                                            <svg width="20" height="20" viewBox="0 0 48 48" fill="none"
                                                xmlns="http://www.w3.org/2000/svg">
                                                <path
                                                    d="M32 18H16C9.37258 18 4 23.3726 4 30C4 36.6274 9.37258 42 16 42H32C38.6274 42 44 36.6274 44 30C44 23.3726 38.6274 18 32 18Z"
                                                    fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                                <path d="M16 26V34" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                    stroke-linejoin="round" />
                                                <path d="M12 30H20" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                    stroke-linejoin="round" />
                                                <path d="M24 16V9.71429H32V4" stroke="#000000" stroke-width="2" stroke-linecap="round"
                                                    stroke-linejoin="round" />
                                                <path
                                                    d="M32 34C34.2091 34 36 32.2091 36 30C36 27.7909 34.2091 26 32 26C29.7909 26 28 27.7909 28 30C28 32.2091 29.7909 34 32 34Z"
                                                    fill="none" stroke="#000000" stroke-width="2" stroke-linejoin="round" />
                                            </svg>
                                            <span><?= $game['game_played'] ?></span>
                                        </div>
                                    </a>
                                    <div class="game-details flex flex-col px-2 mt-2">
                                        <a data-ajax="true" data-href="/<?= $game['game_slug'] ?>"
                                            class="text-2xl text-[var(--common-color)] game-name"
                                            href="<?= $site_url . $game['game_slug'] ?>"><?= $game['game_name'] ?></a>
                                        <a data-ajax="true" data-href="/<?= $game['slug'] ?>"
                                            class="text-md text-[var(--common-color-muted)] mt-1 capitalize"
                                            href="<?= $site_url . makeSlug($game['game_category']) ?>"><?= $game['game_category'] ?></a>
                                    </div>
                                </div>
                            <?php } ?>
                        </div>
                    </div>
                    <div onclick="SlideRight(350, this)" class="right slide-controller">
                        <div class="icon">&RightArrow;</div>
                    </div>
                </div>
            </section>
        <?php } ?>
    <?php } ?>
<?php } else { ?>
    <style>
        .message-box h2 {
            color: var(--common-color);
        }

        .message-box p {
            color: var(--common-color-muted);
        }
    </style>
    <div class="message-box">
        <h2 class="text-3xl">You don't have Featured games to display</h2>
        <p>Please add at least one featured game only then there will be game shows here</p>
    </div>
<?php } ?>