<?php 
global $zon;
$category_name = urldecode(htmlspecialchars($_GET['n'] ?? $zon['page'][1]));
$category_name = $_GET['n'] ?? $zon['page'][1];
?>
<h1 class="text-3xl capitalize mb-8 mt-3 block page-heading" ><?php echo $category_name ?></h1>
<div id="zon_games" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-2 lg:grid-cols-4 xl:grid-cols-6 gap-6"></div>
<div id="zon-loader" class="grid grid-cols-1 sm:grid-cols-2 md:grid-cols-3 lg:grid-cols-4 xl:grid-cols-5 gap-4">
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
    <div class="h-32 w-full" style="background: var(--zon-body-bg-color); box-shadow: 0px 0px 40px 0px var(--zon-search-bg-color);"></div>
</div>